### ISSUE TITLE
Will this library work for function hooking native methods?

### ISSUE THREAD

**Issue by gurrenm3** [monkey0506/native-generic-delegates#13]
It's amazing that your library is able to use generic delegates in native methods. Is it possible to use it in function hooking as well?

**Comment by monkey0506** [comment]
Hi, sorry for the late response. This project is designed to facilitate the gap between [Marshal.GetDelegateForFunctionPointer](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getdelegateforfunctionpointer?view=net-8.0), [Marshal.GetFunctionPointerForDelegate](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getfunctionpointerfordelegate?view=net-8.0), and [generics](https://learn.microsoft.com/en-us/dotnet/standard/generics/). The original version (v1.0.0) did this by generating types at runtime using the `System.Reflection.Emit` library. The generated types have the same function signature as the provided generic `interface`s, but the underlying `delegate` is **not** generic. The new version (in progress, in the `incremental-generator` branch) instead generates those types at compile-time.

There is no specific mechanic that this project exposes that would facilitate an implementation detail like function hooking, and that is outside of the scope of this project. However, if you did have an *existing* hooked function in native code that you wanted to call from managed code, you could accomplish this by exposing the hooked function's address and using one of the `FromFunctionPointer` methods to create a native generic delegate. If you wanted to invoke managed code inside the function body of the hooked function, you could similarly do that by using this project to create a native generic delegate from the managed delegate and use `GetFunctionPointer` to get the native function pointer that can be called from native code.

I hope that helps answer your question.
